# Use the official Nginx image
FROM nginx:latest

# Copy Nginx configuration file to the container
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Expose port 80 for Nginx
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
